### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by sonofevil** [ePirat/Postfish#4]
Sorry for being a dumbass, but I thought this app was supposed to have some kind of GUI...

After I make install, all I seem to get however is a command line tool.

I'm also not sure how to integrate this with Audacity.

**Comment by basilgohar** [comment]
@sonofevil In order to get the GUI you'll need to provide a WAV file as input, for example:

`postfish < input.wav > output.wav`

I, too, am not sure how to integrate with Audacity.  Is there some reference somewhere to that being possible?

**Comment by sonofevil** [comment]
I see, thank you.

Yes it says in the readme that it's "intended to be used with an audio editor such as Audacity"

I interpreted that as meaning that there is some way to invoke it from within Audacity, which seems natural considering it accepts WAV files.

**Comment by basilgohar** [comment]
> I see, thank you.
> 
> Yes it says in the readme that it's "intended to be used with an audio editor such as Audacity"
> 
> I interpreted that as meaning that there is some way to invoke it from within Audacity, which seems natural considering it accepts WAV files.

I see.  That's definitely something you can do by chaining the inputs/outputs via pipelines.

**Comment by sonofevil** [comment]
Okay, I guess you could go to "export audio", select "external program" and enter something like

`ffmpeg -i pipe:0 -f wav pipe:1 | postfish`

However, for some reason ffmpeg then prints `Unable to find a suitable output format for '|'
|: Invalid argument`, even though it's exactly the pipe syntax detailed in the FFmpeg documentation at https://ffmpeg.org/ffmpeg-protocols.html#pipe . Maybe I should just write a script.

But that's not really a postfish issue of course. As far as I'm concerned this issue can be closed. Thanks for the help.
